trigger:
- master
- dev

stages:
- stage: Build
  jobs:
  - job: build
    strategy:
      matrix:
        linux: { imageName: "ubuntu-18.04" }
        mac: { imageName: "macos-10.14" }
        windows: { imageName: "windows-2019" }
      maxParallel: 3
    pool:
      vmImage: $(imageName)

    workspace:
      clean: all

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
        workingDirectory: "$(Pipeline.Workspace)/s/kmd-momentum-mea-client/"

    - task: DotNetCoreCLI@2
      displayName: "Build Solution"
      condition: succeeded()
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      inputs:
        command: build
        projects: './kmd-momentum-mea-client/Kmd-Momentum-Mea-Client.sln'
        arguments: '--configuration "Release"'

- stage: deploy_phoenix
  condition: succeeded()
  dependsOn: Build
  jobs:
  - job:
    pool:
      vmImage: "ubuntu-18.04"

    workspace:
      clean: all

    steps:
    - task: UseDotNet@2
      condition: succeeded()
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
        workingDirectory: "$(Pipeline.Workspace)/s/kmd-momentum-mea-client/"

    - task: DotNetCoreCLI@2
      displayName: "Build NuGet"
      condition: succeeded()
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      inputs:
        command: build
        projects: './kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Create NuGet Package'
      condition: succeeded()
      inputs:
        command: pack        
        packagesToPack: './kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'
        buildProperties: 'VersionSuffix="phoenix$(Build.BuildId)"'
        packDirectory: '$(Build.ArtifactStagingDirectory)/packages/phoenix'
        verbosityPack: 'normal'

    - publish: '$(Build.ArtifactStagingDirectory)/packages/phoenix'
      displayName: 'upload NuGet Package'
      artifact: 'phoenix'

    - task: DotNetCoreCLI@2
      displayName: 'Push NuGet Package'
      condition: succeeded()
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/phoenix/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'phoenix'

- stage: deploy_internal
  condition: succeeded()
  dependsOn: Build
  jobs:
  - job:
    pool:
      vmImage: "ubuntu-18.04"

    workspace:
      clean: all

    steps:
    - task: UseDotNet@2
      condition: succeeded()
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
        workingDirectory: "$(Pipeline.Workspace)/s/kmd-momentum-mea-client/"

    - task: DotNetCoreCLI@2
      displayName: "Build NuGet"
      condition: succeeded()
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      inputs:
        command: build
        projects: './kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Create NuGet Package'
      condition: succeeded()
      inputs:
        command: pack        
        packagesToPack: './kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'
        buildProperties: 'VersionSuffix="internal$(Build.BuildId)"'
        packDirectory: '$(Build.ArtifactStagingDirectory)/packages/internal'
        verbosityPack: 'normal'

    - publish: '$(Build.ArtifactStagingDirectory)/packages/internal'
      displayName: 'upload NuGet Package'
      artifact: 'internal'

    - task: DotNetCoreCLI@2
      displayName: 'Push NuGet Package'
      condition: succeeded()
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/internal/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'internal'

- stage: deploy_external
  condition: succeeded()
  dependsOn: Build
  jobs:
  - job:
    pool:
      vmImage: "ubuntu-18.04"

    workspace:
      clean: all

    steps:
    - task: UseDotNet@2
      condition: succeeded()
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
        workingDirectory: "$(Pipeline.Workspace)/s/kmd-momentum-mea-client/"

    - task: DotNetCoreCLI@2
      displayName: "Build NuGet"
      condition: succeeded()
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      inputs:
        command: build
        projects: './kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Create NuGet Package'
      condition: succeeded()
      inputs:
        command: pack        
        packagesToPack: './kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'
        packDirectory: '$(Build.ArtifactStagingDirectory)/packages/external'
        verbosityPack: 'normal'

    - publish: '$(Build.ArtifactStagingDirectory)/packages/external'
      displayName: 'upload NuGet Package'
      artifact: 'external'

    - task: DotNetCoreCLI@2
      displayName: 'Push NuGet Package'
      condition: succeeded()
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/external/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'test nuget'
