// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssignedActors
    {
        /// <summary>
        /// Initializes a new instance of the AssignedActors class.
        /// </summary>
        public AssignedActors()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssignedActors class.
        /// </summary>
        public AssignedActors(System.Guid? id = default(System.Guid?), string displayName = default(string))
        {
            Id = id;
            DisplayName = displayName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

    }
}
