// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CaseworkerDataResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the CaseworkerDataResponseModel
        /// class.
        /// </summary>
        public CaseworkerDataResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CaseworkerDataResponseModel
        /// class.
        /// </summary>
        public CaseworkerDataResponseModel(string caseworkerId = default(string), string displayName = default(string), string givenName = default(string), string middleName = default(string), string initials = default(string), string email = default(string), string phone = default(string), string caseworkerIdentifier = default(string), string description = default(string), bool? isBookable = default(bool?), bool? isActive = default(bool?))
        {
            CaseworkerId = caseworkerId;
            DisplayName = displayName;
            GivenName = givenName;
            MiddleName = middleName;
            Initials = initials;
            Email = email;
            Phone = phone;
            CaseworkerIdentifier = caseworkerIdentifier;
            Description = description;
            IsBookable = isBookable;
            IsActive = isActive;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "caseworkerId")]
        public string CaseworkerId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "givenName")]
        public string GivenName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "middleName")]
        public string MiddleName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "initials")]
        public string Initials { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "caseworkerIdentifier")]
        public string CaseworkerIdentifier { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isBookable")]
        public bool? IsBookable { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public bool? IsActive { get; private set; }

    }
}
