// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CitizenList
    {
        /// <summary>
        /// Initializes a new instance of the CitizenList class.
        /// </summary>
        public CitizenList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CitizenList class.
        /// </summary>
        public CitizenList(int? totalNoOfPages = default(int?), int? totalSearchCount = default(int?), int? pageNo = default(int?), IList<CitizenDataResponseModel> result = default(IList<CitizenDataResponseModel>))
        {
            TotalNoOfPages = totalNoOfPages;
            TotalSearchCount = totalSearchCount;
            PageNo = pageNo;
            Result = result;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalNoOfPages")]
        public int? TotalNoOfPages { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalSearchCount")]
        public int? TotalSearchCount { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pageNo")]
        public int? PageNo { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "result")]
        public IList<CitizenDataResponseModel> Result { get; private set; }

    }
}
