// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CustomAttributeData
    {
        /// <summary>
        /// Initializes a new instance of the CustomAttributeData class.
        /// </summary>
        public CustomAttributeData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomAttributeData class.
        /// </summary>
        public CustomAttributeData(Type attributeType = default(Type), IList<CustomAttributeTypedArgument> constructorArguments = default(IList<CustomAttributeTypedArgument>), IList<CustomAttributeNamedArgument> namedArguments = default(IList<CustomAttributeNamedArgument>))
        {
            AttributeType = attributeType;
            ConstructorArguments = constructorArguments;
            NamedArguments = namedArguments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attributeType")]
        public Type AttributeType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "constructorArguments")]
        public IList<CustomAttributeTypedArgument> ConstructorArguments { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "namedArguments")]
        public IList<CustomAttributeNamedArgument> NamedArguments { get; private set; }

    }
}
