// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EventInfo
    {
        /// <summary>
        /// Initializes a new instance of the EventInfo class.
        /// </summary>
        public EventInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EventInfo class.
        /// </summary>
        /// <param name="memberType">Possible values include: 'Constructor',
        /// 'Event', 'Field', 'Method', 'Property', 'TypeInfo', 'Custom',
        /// 'NestedType', 'All'</param>
        /// <param name="attributes">Possible values include: 'None',
        /// 'SpecialName', 'ReservedMask', 'ReservedMask'</param>
        /// <param name="isSpecialName"></param>
        /// <param name="addMethod"></param>
        /// <param name="removeMethod"></param>
        /// <param name="raiseMethod"></param>
        /// <param name="isMulticast"></param>
        /// <param name="eventHandlerType"></param>
        /// <param name="name"></param>
        /// <param name="declaringType"></param>
        /// <param name="reflectedType"></param>
        /// <param name="module"></param>
        /// <param name="customAttributes"></param>
        /// <param name="isCollectible"></param>
        /// <param name="metadataToken"></param>
        public EventInfo(string memberType = default(string), string attributes = default(string), bool? isSpecialName = default(bool?), MethodInfo addMethod = default(MethodInfo), MethodInfo removeMethod = default(MethodInfo), MethodInfo raiseMethod = default(MethodInfo), bool? isMulticast = default(bool?), Type eventHandlerType = default(Type), string name = default(string), Type declaringType = default(Type), Type reflectedType = default(Type), Module module = default(Module), IList<CustomAttributeData> customAttributes = default(IList<CustomAttributeData>), bool? isCollectible = default(bool?), int? metadataToken = default(int?))
        {
            MemberType = memberType;
            Attributes = attributes;
            IsSpecialName = isSpecialName;
            AddMethod = addMethod;
            RemoveMethod = removeMethod;
            RaiseMethod = raiseMethod;
            IsMulticast = isMulticast;
            EventHandlerType = eventHandlerType;
            Name = name;
            DeclaringType = declaringType;
            ReflectedType = reflectedType;
            Module = module;
            CustomAttributes = customAttributes;
            IsCollectible = isCollectible;
            MetadataToken = metadataToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Constructor', 'Event',
        /// 'Field', 'Method', 'Property', 'TypeInfo', 'Custom', 'NestedType',
        /// 'All'
        /// </summary>
        [JsonProperty(PropertyName = "memberType")]
        public string MemberType { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'SpecialName',
        /// 'ReservedMask', 'ReservedMask'
        /// </summary>
        [JsonProperty(PropertyName = "attributes")]
        public string Attributes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isSpecialName")]
        public bool? IsSpecialName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addMethod")]
        public MethodInfo AddMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "removeMethod")]
        public MethodInfo RemoveMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "raiseMethod")]
        public MethodInfo RaiseMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isMulticast")]
        public bool? IsMulticast { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventHandlerType")]
        public Type EventHandlerType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "declaringType")]
        public Type DeclaringType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reflectedType")]
        public Type ReflectedType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "module")]
        public Module Module { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customAttributes")]
        public IList<CustomAttributeData> CustomAttributes { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isCollectible")]
        public bool? IsCollectible { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadataToken")]
        public int? MetadataToken { get; private set; }

    }
}
