// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Exception
    {
        /// <summary>
        /// Initializes a new instance of the Exception class.
        /// </summary>
        public Exception()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Exception class.
        /// </summary>
        public Exception(MethodBase targetSite = default(MethodBase), string stackTrace = default(string), string message = default(string), IDictionary<string, object> data = default(IDictionary<string, object>), Exception innerException = default(Exception), string helpLink = default(string), string source = default(string), int? hResult = default(int?))
        {
            TargetSite = targetSite;
            StackTrace = stackTrace;
            Message = message;
            Data = data;
            InnerException = innerException;
            HelpLink = helpLink;
            Source = source;
            HResult = hResult;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "targetSite")]
        public MethodBase TargetSite { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stackTrace")]
        public string StackTrace { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IDictionary<string, object> Data { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "innerException")]
        public Exception InnerException { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "helpLink")]
        public string HelpLink { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hResult")]
        public int? HResult { get; set; }

    }
}
