// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class HealthReport
    {
        /// <summary>
        /// Initializes a new instance of the HealthReport class.
        /// </summary>
        public HealthReport()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HealthReport class.
        /// </summary>
        /// <param name="entries"></param>
        /// <param name="status">Possible values include: 'Unhealthy',
        /// 'Degraded', 'Healthy'</param>
        /// <param name="totalDuration"></param>
        public HealthReport(IDictionary<string, HealthReportEntry> entries = default(IDictionary<string, HealthReportEntry>), string status = default(string), TimeSpan totalDuration = default(TimeSpan))
        {
            Entries = entries;
            Status = status;
            TotalDuration = totalDuration;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entries")]
        public IDictionary<string, HealthReportEntry> Entries { get; private set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unhealthy', 'Degraded',
        /// 'Healthy'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalDuration")]
        public TimeSpan TotalDuration { get; set; }

    }
}
