// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class JournalNoteRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the JournalNoteRequestModel class.
        /// </summary>
        public JournalNoteRequestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JournalNoteRequestModel class.
        /// </summary>
        /// <param name="cpr"></param>
        /// <param name="title"></param>
        /// <param name="type">Possible values include: 'SMS', 'OTHER'</param>
        /// <param name="body"></param>
        /// <param name="documents"></param>
        public JournalNoteRequestModel(string cpr = default(string), string title = default(string), string type = default(string), string body = default(string), IList<JournalNoteDocumentRequestModel> documents = default(IList<JournalNoteDocumentRequestModel>))
        {
            Cpr = cpr;
            Title = title;
            Type = type;
            Body = body;
            Documents = documents;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cpr")]
        public string Cpr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'SMS', 'OTHER'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documents")]
        public IList<JournalNoteDocumentRequestModel> Documents { get; set; }

    }
}
