// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Module
    {
        /// <summary>
        /// Initializes a new instance of the Module class.
        /// </summary>
        public Module()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Module class.
        /// </summary>
        public Module(Assembly assembly = default(Assembly), string fullyQualifiedName = default(string), string name = default(string), int? mdStreamVersion = default(int?), System.Guid? moduleVersionId = default(System.Guid?), string scopeName = default(string), ModuleHandle moduleHandle = default(ModuleHandle), IList<CustomAttributeData> customAttributes = default(IList<CustomAttributeData>), int? metadataToken = default(int?))
        {
            Assembly = assembly;
            FullyQualifiedName = fullyQualifiedName;
            Name = name;
            MdStreamVersion = mdStreamVersion;
            ModuleVersionId = moduleVersionId;
            ScopeName = scopeName;
            ModuleHandle = moduleHandle;
            CustomAttributes = customAttributes;
            MetadataToken = metadataToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assembly")]
        public Assembly Assembly { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fullyQualifiedName")]
        public string FullyQualifiedName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mdStreamVersion")]
        public int? MdStreamVersion { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "moduleVersionId")]
        public System.Guid? ModuleVersionId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scopeName")]
        public string ScopeName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "moduleHandle")]
        public ModuleHandle ModuleHandle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customAttributes")]
        public IList<CustomAttributeData> CustomAttributes { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadataToken")]
        public int? MetadataToken { get; private set; }

    }
}
