// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Participants
    {
        /// <summary>
        /// Initializes a new instance of the Participants class.
        /// </summary>
        public Participants()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Participants class.
        /// </summary>
        public Participants(System.Guid? actorId = default(System.Guid?), int? responsibility = default(int?))
        {
            ActorId = actorId;
            Responsibility = responsibility;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "actorId")]
        public System.Guid? ActorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsibility")]
        public int? Responsibility { get; set; }

    }
}
