// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Phone
    {
        /// <summary>
        /// Initializes a new instance of the Phone class.
        /// </summary>
        public Phone()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Phone class.
        /// </summary>
        public Phone(string id = default(string), string number = default(string), bool? isMobile = default(bool?))
        {
            Id = id;
            Number = number;
            IsMobile = isMobile;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isMobile")]
        public bool? IsMobile { get; set; }

    }
}
