// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TaskUpdateStatus
    {
        /// <summary>
        /// Initializes a new instance of the TaskUpdateStatus class.
        /// </summary>
        public TaskUpdateStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaskUpdateStatus class.
        /// </summary>
        /// <param name="taskAction">Possible values include: 'Completed',
        /// 'Cancel', 'Delete', 'Start'</param>
        /// <param name="taskContext">Possible values include: 'Citizens',
        /// 'Companies', 'Offers', 'Dashboard', 'Admin', 'Search'</param>
        public TaskUpdateStatus(string taskAction = default(string), string taskContext = default(string))
        {
            TaskAction = taskAction;
            TaskContext = taskContext;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Completed', 'Cancel',
        /// 'Delete', 'Start'
        /// </summary>
        [JsonProperty(PropertyName = "taskAction")]
        public string TaskAction { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Citizens', 'Companies',
        /// 'Offers', 'Dashboard', 'Admin', 'Search'
        /// </summary>
        [JsonProperty(PropertyName = "taskContext")]
        public string TaskContext { get; set; }

    }
}
